name: Ruby on Rails

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rails_version: [5.2.6, 6.1.4]
                ruby_version: [2.5, 2.6, 2.7, '3.0']
                exclude:
                    - rails_version: 5.2.6
                      ruby_version: '3.0'
                include:
                    - rails_version: 7.0.2.3
                      ruby_version: '3.0'
                    - rails_version: 7.0.2.3
                      ruby_version: 3.1
                    - rails_version: 7.0.2.3
                      ruby_version: 3.2
        steps:
            - uses: actions/checkout@v3
            - name: Cache
              uses: actions/cache@v3
              with:
                  path: vendor/bundle
                  key: ${{ matrix.ruby_version }}_${{ matrix.rails_version }}
            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: ${{ matrix.ruby_version }}
            - name: Build and test with Rake
              run: |
                  sudo apt-get install libsqlite3-dev
                  rm Gemfile.lock
                  gem install bundler
                  bundle install --path vendor/bundle --jobs 4 --retry 3
                  bundle exec rake
              env:
                  RAILS_VERSION: ${{ matrix.rails_version }}
                  ON_CI: true
